# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud-mcp" do
  version "0.0.26"

  on_macos do
    sha256 "29ffb786b7522d7da65178369a65778adffde7aadfd185a5fed65cfd93a1a65e"
    url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_macOS_all.tar.gz",
        verified: "github.com/simplifyd-systems/cloud-mcp"
  end
  on_linux do
    on_arm do
      sha256 "5e55dacfc0cd8700fbc3b8f99dea9c868298600e7119922b8f0b9cfffe8b8fd0"
      url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/simplifyd-systems/cloud-mcp"
    end
    on_intel do
      sha256 "569035264bb0f5c241d301b20f425cd17a45e95133c803eb38eecebaecead949"
      url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/simplifyd-systems/cloud-mcp"
    end
  end

  name "cloud-mcp"
  desc "Simplifyd Cloud MCP Server - manage cloud resources via the Model Context Protocol"
  homepage "https://github.com/simplifyd-systems/cloud-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud-mcp"

  # No zap stanza required
end
