# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud-mcp" do
  version "0.0.31"

  on_macos do
    sha256 "09b006b71484a38a1256105b4d691dad9eeb98c692967cee4ec781336986b8fd"
    url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_macOS_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "d1d1d9176b37cf8ea8258d10a70573899f94484d08ccf80b284371283a67474e"
      url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "778e7cb12031b17efe92d74fe7156859e0ce48b30fbe7dcb4c79103386fb298c"
      url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "cloud-mcp"
  desc "Simplifyd Cloud MCP Server - manage cloud resources via the Model Context Protocol"
  homepage "https://github.com/simplifyd-systems/cloud-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud-mcp"

  # No zap stanza required
end
