# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud-mcp" do
  version "0.0.8"

  on_macos do
    sha256 "aef9aa295dbd0cf2b02887c4098c5ef18666a02ef9cd52636744c9ac8167674d"
    url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_macOS_all.tar.gz",
        verified: "github.com/simplifyd-systems/cloud-mcp"
  end

  on_linux do
    on_intel do
      sha256 "f95da66b227df2c6d8170e42617b7eced568d3da55fd4617f1e9438cdd769528"
      url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/simplifyd-systems/cloud-mcp"
    end
    on_arm do
      sha256 "ec23c7698df7d5fc98619a8295eccec48d1039db7247d89d9da1b4e856c355ce"
      url "https://github.com/simplifyd-systems/cloud-mcp/releases/download/v#{version}/cloud-mcp_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/simplifyd-systems/cloud-mcp"
    end
  end

  name "cloud-mcp"
  desc "Simplifyd Cloud MCP Server - manage cloud resources via the Model Context Protocol"
  homepage "https://github.com/simplifyd-systems/cloud-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud-mcp"

  # No zap stanza required

end
