# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edge < Formula
  desc "Simplifyd Cloud CLI — manage cloud resources from the terminal"
  homepage "https://github.com/simplifyd-systems/cloud-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    url "https://github.com/simplifyd-systems/cli/releases/download/v0.1.2/edge_0.1.2_macOS_all.tar.gz"
    sha256 "28ac5b0745de2dc2bd64c3681e14bc442e13cf6a79da37c72ee8b1ed197f9674"

    define_method(:install) do
      bin.install "edge"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simplifyd-systems/cli/releases/download/v0.1.2/edge_0.1.2_Linux_x86_64.tar.gz"
      sha256 "85bbf3a55a3ba20a6d1f0981f781bcbb5079c1c4b2338943048df4894cb81c2e"
      define_method(:install) do
        bin.install "edge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simplifyd-systems/cli/releases/download/v0.1.2/edge_0.1.2_Linux_arm64.tar.gz"
      sha256 "ec494a4edbb305e345dc5c2f094d24347ce712f3bb2362f3d2485bb8de6a665d"
      define_method(:install) do
        bin.install "edge"
      end
    end
  end

  test do
    system "#{bin}/edge", "--version"
  end
end
