# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edge < Formula
  desc "Simplifyd Cloud CLI — manage cloud resources from the terminal"
  homepage "https://github.com/simplifyd-systems/cloud-cli"
  version "0.1.38"
  license "MIT"

  on_macos do
    url "https://github.com/simplifyd-systems/cli/releases/download/v0.1.38/edge_0.1.38_macOS_all.tar.gz"
    sha256 "c21b8b2ad8438e9d8cc03955c73f30470e335a85f23b3f7b9d60fbfae0404fc5"

    define_method(:install) do
      bin.install "edge"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simplifyd-systems/cli/releases/download/v0.1.38/edge_0.1.38_Linux_x86_64.tar.gz"
      sha256 "a0fb5367518be2d73d132d014666ee4ce3e29378241d656c63e51e6114dc816f"
      define_method(:install) do
        bin.install "edge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simplifyd-systems/cli/releases/download/v0.1.38/edge_0.1.38_Linux_arm64.tar.gz"
      sha256 "4f5db45b7d1c4e1ad167f16453ead9d45f8a1d910f5158e51686ae74912318d0"
      define_method(:install) do
        bin.install "edge"
      end
    end
  end

  test do
    system "#{bin}/edge", "version"
  end
end
